services:
  - docker

before_install:
  - docker pull pickandwhammy/cpp17-sfml:0.2

install:
  - docker run -v $PWD:/workspace -it pickandwhammy/cpp17-sfml:0.2 /bin/sh -c "chmod a+x .ci/*.sh && .ci/start.sh"

script: 
  - echo "Success"
