language: cpp

services:
  - docker

before_install:
  - docker pull pickandwhammy/cpp17-sfml:0.2

install:
  - docker run -v $PWD:/workspace -it pickandwhammy/cpp17-sfml:0.2 chmod a+x .ci/*.sh && .ci/start.sh
